export const GET_PARKING_SPOTS = "GET_PARKING_SPOTS";
export const ADD_PARKING_SPOT = "ADD_PARKING_SPOT";
export const REMOVE_PARKING_SPOT = "REMOVE_PARKING_SPOT";
export const GET_RADIUS = "GET_RADIUS";
export const SET_RADIUS = "SET_RADIUS";
export const GET_SEARCH_LOCATION = "GET_SEARCH_LOCATION";
export const SET_SEARCH_LOCATION = "SET_SEARCH_LOCATION";